# -*- coding: utf-8 -*-
"""automate_Monica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WwfTJF_XXH_BJqZARbI3_508tCjSBuT1
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import os

def preprocess_data(input_path, output_dir):
    # Load dataset
    df = pd.read_csv(input_path)

    # Encode diagnosis: 'M' → 1, 'B' → 0
    df['diagnosis'] = LabelEncoder().fit_transform(df['diagnosis'])

    # Pisahkan fitur dan target
    x = df.drop(['diagnosis'], axis=1)
    y = df['diagnosis']

    # Split data (80% train, 20% test)
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

    # Standardisasi fitur
    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    # Pastikan folder output ada
    os.makedirs(output_dir, exist_ok=True)

    # Simpan hasil preprocessing ke CSV
    pd.DataFrame(x_train_scaled, columns=x.columns).to_csv(f"{output_dir}/x_train.csv", index=False)
    pd.DataFrame(x_test_scaled, columns=x.columns).to_csv(f"{output_dir}/x_test.csv", index=False)
    pd.DataFrame(y_train).to_csv(f"{output_dir}/y_train.csv", index=False)
    pd.DataFrame(y_test).to_csv(f"{output_dir}/y_test.csv", index=False)

    print("✅ Preprocessing selesai. Dataset disimpan di folder:", output_dir)

if __name__ == '__main__':
    input_file = 'data.csv'
    output_folder = 'preprocessing/data_preprocessing'
    preprocess_data(input_file, output_folder)

