name: Preprocess Dataset

on:
  push:
    branches:
      - main
      

permissions:
  contents: write  
  
jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn mlflow
      
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_monica.py

      - name: Set up Git credentials
        run: |
         git config --global user.name "github-actions"
         git config --global user.email "github-actions@github.com"
         git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push processed data
        run: |
          git add preprocessing/data_preprocessing/*
          git commit -m "Preprocessed data update" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
